### ISSUE TITLE
method `method_missing' called on terminated object

### ISSUE THREAD

**Issue by emorikawa** [cowboyd/less.rb#70]
Occasionaly when compiling a large asset, I will get the error:

```
error evaluating function `font-url`: method `method_missing' called on terminated object (0x00000007901aa8 flags=0x0 klass=0x0)
```

Other people seem to have this problem:
https://github.com/cowboyd/therubyracer/issues/176
https://github.com/sparklemotion/sqlite3-ruby/issues/60
https://github.com/senchalabs/jsduck/issues/396

@tenderlove Seems to have fixed this in another project with `RB_GC_GUARD`. See https://github.com/sparklemotion/sqlite3-ruby/commit/dd9ded98633ece40f9794464e82bb7646028753e

Here's a stack trace with the problem (via less-rails and sprockets)

```
   error evaluating function `font-url`: method `method_missing' called on terminated object (0x00000007901aa8 flags=0x0 klass=0x0)
   (in /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/app/assets/stylesheets/manifests/communities.css.less)
   at /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/js/lib/less/parser.js:424:31
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/parser.rb:100:in `block in to_css'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/java_script/v8_context.rb:90:in `block in do_lock'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/java_script/v8_context.rb:88:in `call'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/java_script/v8_context.rb:88:in `Locker'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/java_script/v8_context.rb:88:in `do_lock'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/java_script/v8_context.rb:60:in `lock'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/java_script/v8_context.rb:30:in `exec'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/java_script.rb:26:in `exec'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-2.4.0/lib/less/parser.rb:100:in `to_css'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/less-rails-2.4.2/lib/less/rails/template_handlers.rb:19:in `evaluate'
   /tmp/build_5383504b-9067-43c4-b2c0-69570b35b89e/vendor/bundle/ruby/1.9.1/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
```

**Comment by bhargavd** [comment]
@emorikawa we are getting the same error. How did you resolve this issue? Please help
