### ISSUE TITLE
“Maximum call stack size exceeded” when using Fibers

### ISSUE THREAD

**Issue by denisdefreyne** [cowboyd/less.rb#82]
The following code snippet raises an exception:

```ruby
require 'less'

Fiber.new do
  ::Less::Parser.new.parse("p { color: red }")
end.resume
```

The exception:

```
/var/lib/gems/2.1.0/gems/less-2.6.0/lib/less/parser.rb:55:in `block in initialize': Maximum call stack size exceeded (Less::Error)
	from /var/lib/gems/2.1.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:90:in `block in do_lock'
	from /var/lib/gems/2.1.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:88:in `call'
	from /var/lib/gems/2.1.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:88:in `Locker'
	from /var/lib/gems/2.1.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:88:in `do_lock'
	from /var/lib/gems/2.1.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:60:in `lock'
	from /var/lib/gems/2.1.0/gems/less-2.6.0/lib/less/java_script/v8_context.rb:30:in `exec'
	from /var/lib/gems/2.1.0/gems/less-2.6.0/lib/less/java_script.rb:26:in `exec'
	from /var/lib/gems/2.1.0/gems/less-2.6.0/lib/less/parser.rb:55:in `initialize'
	from less_fiber_test_a.rb:4:in `new'
	from less_fiber_test_a.rb:4:in `block in <main>'
```

The following code snippet works, however:

```ruby
require 'less'

::Less::Parser.new.parse("p { color: red }")
```

The exception occurs on Linux (tested on Debian), but not on macOS. Here is a Vagrantfile that sets up a usable machine for testing the example:

```
Vagrant.configure("2") do |config|
  config.vm.box = "minimal/jessie64"

  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      DEBIAN_FRONTEND=noninteractive apt-get -y update
      DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential
      DEBIAN_FRONTEND=noninteractive apt-get -y install openssl
      DEBIAN_FRONTEND=noninteractive apt-get -y install ruby
      DEBIAN_FRONTEND=noninteractive apt-get -y install ruby-dev

      gem install therubyracer
      gem install less
    SHELL
  end
end
```

**Comment by denisdefreyne** [comment]
This appears to be a problem with V8 or Ruby’s interface to V8, as the following also errors:

```
require 'v8'

context = V8::Context.new

Fiber.new do
  context.eval("console.log('hi')")
end.resume
```

Will close this issue for now, as it’s not one in less.rb.
